---
apiVersion: apis.kcp.dev/v1alpha1
kind: APIExport
metadata:
  name: gitopsrvc-appstudio-shared
spec:
  permissionClaims:
  - group: ""
    resource: secrets
  - group: ""
    resource: namespaces
  - group: managed-gitops.redhat.com
    identityHash: 6c6a1d4b80df0ab055516e69c05dfef25ec5d0952840a5310e90d74fd22ea777
    resource: gitopsdeployments
  - group: appstudio.redhat.com
    identityHash: 9ff5f6d487f212274327768be0fa49b1133b8587cfa5e6563396097810f30a32
    resource: applications
  - group: appstudio.redhat.com
    identityHash: 9ff5f6d487f212274327768be0fa49b1133b8587cfa5e6563396097810f30a32
    resource: applicationsnapshotenvironmentbindings
  - group: appstudio.redhat.com
    identityHash: 9ff5f6d487f212274327768be0fa49b1133b8587cfa5e6563396097810f30a32
    resource: components
  - group: appstudio.redhat.com
    identityHash: 9ff5f6d487f212274327768be0fa49b1133b8587cfa5e6563396097810f30a32
    resource: environments
