---
- op: replace
  path: /spec/template/spec/source/repoURL
  value: https://github.com/jgwest/infra-deployments
- op: replace
  path: /spec/template/spec/source/targetRevision
  value: preview-gitopsrvce-780-update-rbac-nov-2023
