apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/redhat-appstudio/managed-gitops/manifests/kcp?ref=db924ec7d7e44d9b205b103d7d0b05abac3a4f1d

images:
  - name: \${COMMON_IMAGE}
    newName: quay.io/redhat-appstudio/gitops-service
    newTag: d868aef2b5db0f38ca4d6129bf204ee9561df728

