apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/jgwest/managed-gitops/manifests/kcp?ref=577416c20438c112be00fceea59ebd3975443d77
# TODO: Make sure this is replaced with reference to managed-gitops repo!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! (more exclamation marks so it's easy recognizable in PR view :)  )

images:
  - name: \${COMMON_IMAGE}
    newName: quay.io/redhat-appstudio/gitops-service
    newTag: 33705d2bf7faa59cdaa3d6515c1c6480438c15c0

