apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/jgwest/managed-gitops/manifests/kcp?ref=update-kcp-manifests-oct-2022

images:
  - name: \${COMMON_IMAGE}
    newName: quay.io/jgwest-redhat/gitops-service
    newTag: latest

