apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/redhat-appstudio/managed-gitops/manifests/overlays/stonesoup-member-cluster?ref=006efe22e41e6c249d333e0a0f2a87bd32d3bf02
- ../../openshift-gitops/overlays/staging
- ../../base/external-secrets
- ../../base/monitoring
- authentication

images:
  - name: \${COMMON_IMAGE}
    newName: quay.io/redhat-appstudio/gitops-service
    newTag: 87e1f9acc67bf033d2159951ba6489f0836586ef

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
